// <auto-generated />
namespace Portaria.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PesquisaDetalhadaPadrao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PesquisaDetalhadaPadrao));
        
        string IMigrationMetadata.Id
        {
            get { return "201512300306297_PesquisaDetalhadaPadrao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
